// Datos de ejemplo. El sitio los usa solo si no puede leer tu hoja de Google.
window.NEXO_EJEMPLO = {
 "sitio": [
  {
   "clave": "nombre_sitio",
   "valor": "NEXO Académico"
  },
  {
   "clave": "lema",
   "valor": "Todo lo de tus cursos, en un solo lugar."
  },
  {
   "clave": "docente",
   "valor": "MBA. Luis Andrés Córdova Bueno"
  },
  {
   "clave": "saludo",
   "valor": "Hola, bienvenido(a)."
  },
  {
   "clave": "mensaje",
   "valor": "Aquí encontrarás los materiales de cada sesión: saberes esenciales, guías, plantillas y rúbricas, ordenados por semana. Si algo no aparece, usa el buscador."
  },
  {
   "clave": "foto",
   "valor": "foto.jpg"
  },
  {
   "clave": "aviso_acceso",
   "valor": "Los archivos son solo para estudiantes del curso. Se abren con la cuenta de Google con la que te uniste al grupo del curso."
  }
 ],
 "cursos": [
  {
   "codigo": "CINE1248P",
   "nombre": "Producción y Operaciones Sostenibles",
   "universidad": "UPN",
   "ciclo": "4",
   "periodo": "2026-2",
   "modalidad": "Presencial",
   "descripcion": "Gestión de operaciones y producción sostenible: eficiencia operativa, gestión de recursos, economía circular y tecnologías sostenibles.",
   "logro": "Sustentas un reporte académico con una propuesta de optimización del proceso productivo de una organización real, con enfoque ecológico, sustentable y sostenible.",
   "color": "#2E7D6B",
   "aula_virtual": "",
   "grupo": "https://groups.google.com/g/nexo-cine1248p",
   "silabo": "",
   "fecha_inicio": "2026-08-24",
   "semana_actual": "",
   "total_semanas": "16",
   "estado": "Activo",
   "orden": "1"
  }
 ],
 "temas": [
  {
   "curso": "CINE1248P",
   "tema": "1",
   "titulo": "Fundamentos de producción sostenible",
   "capacidad": "Explicar los principios de producción sostenible para comprender su impacto en la competitividad empresarial.",
   "semana_inicio": "1",
   "semana_fin": "2",
   "carpeta": "https://drive.google.com/drive/folders/1XatGEk7lVKKO6Jngu9bCJAzO6kYcrnPc"
  },
  {
   "curso": "CINE1248P",
   "tema": "2",
   "titulo": "Diseño del proceso productivo",
   "capacidad": "Describir los elementos del diseño de procesos para reconocer su influencia en la eficiencia operativa.",
   "semana_inicio": "3",
   "semana_fin": "4",
   "carpeta": "https://drive.google.com/drive/folders/1FMQdthmMJWLVOTRWXcL8pgx9sa8dgOiN"
  },
  {
   "curso": "CINE1248P",
   "tema": "3",
   "titulo": "Métodos de trabajo",
   "capacidad": "Aplicar técnicas de medición del trabajo para proponer mejoras en procesos productivos.",
   "semana_inicio": "5",
   "semana_fin": "6",
   "carpeta": "https://drive.google.com/drive/folders/1m2QW5awaPaE5yGURXDVistVXKlcSVQjo"
  },
  {
   "curso": "CINE1248P",
   "tema": "4",
   "titulo": "Herramientas de control",
   "capacidad": "Analizar herramientas de control para evaluar la calidad y sostenibilidad en la producción.",
   "semana_inicio": "7",
   "semana_fin": "9",
   "carpeta": "https://drive.google.com/drive/folders/1AjKLVb9tHWaZxX2ALijfkZqM8CCEQ9UA"
  },
  {
   "curso": "CINE1248P",
   "tema": "5",
   "titulo": "Planificación y programación",
   "capacidad": "Aplicar métodos de planificación para diseñar planes de producción eficientes y sostenibles.",
   "semana_inicio": "10",
   "semana_fin": "11",
   "carpeta": "https://drive.google.com/drive/folders/10xT_MR9jPzyogftO7LSv78DSrSwVXAd5"
  },
  {
   "curso": "CINE1248P",
   "tema": "6",
   "titulo": "Gestión de proyectos",
   "capacidad": "Analizar técnicas de gestión de proyectos para implementar mejoras en procesos productivos.",
   "semana_inicio": "12",
   "semana_fin": "13",
   "carpeta": "https://drive.google.com/drive/folders/1nM0lkYIhSxs74EKCnIbFFgXBUNW9YuOS"
  },
  {
   "curso": "CINE1248P",
   "tema": "7",
   "titulo": "Innovación y tendencias",
   "capacidad": "Explicar tendencias en producción sostenible para comprender su impacto en la competitividad global.",
   "semana_inicio": "14",
   "semana_fin": "15",
   "carpeta": "https://drive.google.com/drive/folders/1CiSAUd7DfVi7qLXLR2JUdrgpEMKQGOqg"
  }
 ],
 "subtemas": [
  {
   "curso": "CINE1248P",
   "tema": "1",
   "subtema": "1.1",
   "titulo": "Conceptos básicos de producción sostenible"
  },
  {
   "curso": "CINE1248P",
   "tema": "1",
   "subtema": "1.2",
   "titulo": "Principios de sostenibilidad"
  },
  {
   "curso": "CINE1248P",
   "tema": "1",
   "subtema": "1.3",
   "titulo": "Diseño universal y accesibilidad"
  },
  {
   "curso": "CINE1248P",
   "tema": "1",
   "subtema": "1.4",
   "titulo": "Impacto ambiental"
  },
  {
   "curso": "CINE1248P",
   "tema": "2",
   "subtema": "2.1",
   "titulo": "Layout y distribución"
  },
  {
   "curso": "CINE1248P",
   "tema": "2",
   "subtema": "2.2",
   "titulo": "Estrategias de localización"
  },
  {
   "curso": "CINE1248P",
   "tema": "2",
   "subtema": "2.3",
   "titulo": "Ergonomía y accesibilidad"
  },
  {
   "curso": "CINE1248P",
   "tema": "2",
   "subtema": "2.4",
   "titulo": "Optimización de recursos"
  },
  {
   "curso": "CINE1248P",
   "tema": "3",
   "subtema": "3.1",
   "titulo": "Estudio de tiempos y movimientos"
  },
  {
   "curso": "CINE1248P",
   "tema": "3",
   "subtema": "3.2",
   "titulo": "Cursogramas analíticos"
  },
  {
   "curso": "CINE1248P",
   "tema": "3",
   "subtema": "3.3",
   "titulo": "Medición del trabajo"
  },
  {
   "curso": "CINE1248P",
   "tema": "3",
   "subtema": "3.4",
   "titulo": "Control estadístico"
  },
  {
   "curso": "CINE1248P",
   "tema": "4",
   "subtema": "4.1",
   "titulo": "Control estadístico de procesos"
  },
  {
   "curso": "CINE1248P",
   "tema": "4",
   "subtema": "4.2",
   "titulo": "Indicadores de desempeño"
  },
  {
   "curso": "CINE1248P",
   "tema": "4",
   "subtema": "4.3",
   "titulo": "Gestión de riesgos"
  },
  {
   "curso": "CINE1248P",
   "tema": "4",
   "subtema": "4.4",
   "titulo": "Herramientas cualitativas y cuantitativas"
  },
  {
   "curso": "CINE1248P",
   "tema": "5",
   "subtema": "5.1",
   "titulo": "Pronósticos"
  },
  {
   "curso": "CINE1248P",
   "tema": "5",
   "subtema": "5.2",
   "titulo": "Planeación agregada"
  },
  {
   "curso": "CINE1248P",
   "tema": "5",
   "subtema": "5.3",
   "titulo": "MRP"
  },
  {
   "curso": "CINE1248P",
   "tema": "5",
   "subtema": "5.4",
   "titulo": "Optimización de recursos"
  },
  {
   "curso": "CINE1248P",
   "tema": "6",
   "subtema": "6.1",
   "titulo": "CPM"
  },
  {
   "curso": "CINE1248P",
   "tema": "6",
   "subtema": "6.2",
   "titulo": "PERT"
  },
  {
   "curso": "CINE1248P",
   "tema": "6",
   "subtema": "6.3",
   "titulo": "Cronogramas y recursos"
  },
  {
   "curso": "CINE1248P",
   "tema": "6",
   "subtema": "6.4",
   "titulo": "Evaluación de proyectos"
  },
  {
   "curso": "CINE1248P",
   "tema": "7",
   "subtema": "7.1",
   "titulo": "Producción verde"
  },
  {
   "curso": "CINE1248P",
   "tema": "7",
   "subtema": "7.2",
   "titulo": "Economía circular"
  },
  {
   "curso": "CINE1248P",
   "tema": "7",
   "subtema": "7.3",
   "titulo": "Digitalización y automatización"
  },
  {
   "curso": "CINE1248P",
   "tema": "7",
   "subtema": "7.4",
   "titulo": "Retos futuros de la producción sostenible"
  }
 ],
 "recursos": [
  {
   "id": "CINE1248P-T01-PPT",
   "curso": "CINE1248P",
   "tema": "1",
   "subtema": "",
   "semana": "1",
   "tipo": "Presentación",
   "formato": "PowerPoint",
   "titulo": "PPT del Tema 1: Fundamentos de producción sostenible",
   "descripcion": "Presentación de clase que integra los cuatro subtemas del Tema 1.",
   "enlace": "",
   "enlace_externo": "",
   "etiquetas": "sostenibilidad; triple resultado; ODS; ODS; economía verde; triple resultado; accesibilidad; diseño inclusivo; huella de carbono; ACV; impacto ambiental",
   "destacado": "",
   "visibilidad": "Estudiantes",
   "estado": "Activo",
   "actualizado": "2026-08-22",
   "peso": "8,4 MB"
  },
  {
   "id": "CINE1248P-T01-VIDEO",
   "curso": "CINE1248P",
   "tema": "1",
   "subtema": "",
   "semana": "1",
   "tipo": "Video",
   "formato": "Video",
   "titulo": "Video introductorio del Tema 1",
   "descripcion": "Cinco minutos para entender de qué trata fundamentos de producción sostenible y qué harás en el laboratorio.",
   "enlace": "",
   "enlace_externo": "",
   "etiquetas": "",
   "destacado": "",
   "visibilidad": "Estudiantes",
   "estado": "Activo",
   "actualizado": "2026-08-22",
   "peso": ""
  },
  {
   "id": "CINE1248P-T01SUBT11",
   "curso": "CINE1248P",
   "tema": "1",
   "subtema": "1.1",
   "semana": "1",
   "tipo": "Saberes esenciales",
   "formato": "Word",
   "titulo": "Saberes esenciales 1.1: Conceptos básicos de producción sostenible",
   "descripcion": "Guía de estudio con fundamentos, autores clave, casos empresariales de la región, glosario y bibliografía APA 7.",
   "enlace": "",
   "enlace_externo": "",
   "etiquetas": "sostenibilidad; triple resultado; ODS",
   "destacado": "",
   "visibilidad": "Estudiantes",
   "estado": "Activo",
   "actualizado": "2026-08-22",
   "peso": "1,6 MB"
  },
  {
   "id": "CINE1248P-T01SUBT12",
   "curso": "CINE1248P",
   "tema": "1",
   "subtema": "1.2",
   "semana": "1",
   "tipo": "Saberes esenciales",
   "formato": "Word",
   "titulo": "Saberes esenciales 1.2: Principios de sostenibilidad",
   "descripcion": "Guía de estudio con fundamentos, autores clave, casos empresariales de la región, glosario y bibliografía APA 7.",
   "enlace": "",
   "enlace_externo": "",
   "etiquetas": "ODS; economía verde; triple resultado",
   "destacado": "",
   "visibilidad": "Estudiantes",
   "estado": "Activo",
   "actualizado": "2026-08-22",
   "peso": "1,6 MB"
  },
  {
   "id": "CINE1248P-T01SUBT13",
   "curso": "CINE1248P",
   "tema": "1",
   "subtema": "1.3",
   "semana": "2",
   "tipo": "Saberes esenciales",
   "formato": "Word",
   "titulo": "Saberes esenciales 1.3: Diseño universal y accesibilidad",
   "descripcion": "Guía de estudio con fundamentos, autores clave, casos empresariales de la región, glosario y bibliografía APA 7.",
   "enlace": "",
   "enlace_externo": "",
   "etiquetas": "accesibilidad; diseño inclusivo",
   "destacado": "",
   "visibilidad": "Estudiantes",
   "estado": "Activo",
   "actualizado": "2026-08-22",
   "peso": "1,6 MB"
  },
  {
   "id": "CINE1248P-T01SUBT14",
   "curso": "CINE1248P",
   "tema": "1",
   "subtema": "1.4",
   "semana": "2",
   "tipo": "Saberes esenciales",
   "formato": "Word",
   "titulo": "Saberes esenciales 1.4: Impacto ambiental",
   "descripcion": "Guía de estudio con fundamentos, autores clave, casos empresariales de la región, glosario y bibliografía APA 7.",
   "enlace": "",
   "enlace_externo": "",
   "etiquetas": "huella de carbono; ACV; impacto ambiental",
   "destacado": "",
   "visibilidad": "Estudiantes",
   "estado": "Activo",
   "actualizado": "2026-08-22",
   "peso": "1,6 MB"
  },
  {
   "id": "CINE1248P-T02-PPT",
   "curso": "CINE1248P",
   "tema": "2",
   "subtema": "",
   "semana": "3",
   "tipo": "Presentación",
   "formato": "PowerPoint",
   "titulo": "PPT del Tema 2: Diseño del proceso productivo",
   "descripcion": "Presentación de clase que integra los cuatro subtemas del Tema 2.",
   "enlace": "",
   "enlace_externo": "",
   "etiquetas": "layout; distribución de planta; SLP; localización; factores ponderados; centro de gravedad; ergonomía; REBA; RULA; puesto de trabajo; recursos; desperdicios; lean",
   "destacado": "",
   "visibilidad": "Estudiantes",
   "estado": "Activo",
   "actualizado": "2026-09-04",
   "peso": "8,4 MB"
  },
  {
   "id": "CINE1248P-T02-VIDEO",
   "curso": "CINE1248P",
   "tema": "2",
   "subtema": "",
   "semana": "3",
   "tipo": "Video",
   "formato": "Video",
   "titulo": "Video introductorio del Tema 2",
   "descripcion": "Cinco minutos para entender de qué trata diseño del proceso productivo y qué harás en el laboratorio.",
   "enlace": "",
   "enlace_externo": "",
   "etiquetas": "",
   "destacado": "",
   "visibilidad": "Estudiantes",
   "estado": "Activo",
   "actualizado": "2026-09-04",
   "peso": ""
  },
  {
   "id": "CINE1248P-T02SUBT21",
   "curso": "CINE1248P",
   "tema": "2",
   "subtema": "2.1",
   "semana": "3",
   "tipo": "Saberes esenciales",
   "formato": "Word",
   "titulo": "Saberes esenciales 2.1: Layout y distribución",
   "descripcion": "Guía de estudio con fundamentos, autores clave, casos empresariales de la región, glosario y bibliografía APA 7.",
   "enlace": "",
   "enlace_externo": "",
   "etiquetas": "layout; distribución de planta; SLP",
   "destacado": "",
   "visibilidad": "Estudiantes",
   "estado": "Activo",
   "actualizado": "2026-09-04",
   "peso": "1,6 MB"
  },
  {
   "id": "CINE1248P-T02SUBT22",
   "curso": "CINE1248P",
   "tema": "2",
   "subtema": "2.2",
   "semana": "3",
   "tipo": "Saberes esenciales",
   "formato": "Word",
   "titulo": "Saberes esenciales 2.2: Estrategias de localización",
   "descripcion": "Guía de estudio con fundamentos, autores clave, casos empresariales de la región, glosario y bibliografía APA 7.",
   "enlace": "",
   "enlace_externo": "",
   "etiquetas": "localización; factores ponderados; centro de gravedad",
   "destacado": "",
   "visibilidad": "Estudiantes",
   "estado": "Activo",
   "actualizado": "2026-09-04",
   "peso": "1,6 MB"
  },
  {
   "id": "CINE1248P-T02SUBT23",
   "curso": "CINE1248P",
   "tema": "2",
   "subtema": "2.3",
   "semana": "4",
   "tipo": "Saberes esenciales",
   "formato": "Word",
   "titulo": "Saberes esenciales 2.3: Ergonomía y accesibilidad",
   "descripcion": "Guía de estudio con fundamentos, autores clave, casos empresariales de la región, glosario y bibliografía APA 7.",
   "enlace": "",
   "enlace_externo": "",
   "etiquetas": "ergonomía; REBA; RULA; puesto de trabajo",
   "destacado": "",
   "visibilidad": "Estudiantes",
   "estado": "Activo",
   "actualizado": "2026-09-04",
   "peso": "1,6 MB"
  },
  {
   "id": "CINE1248P-T02SUBT24",
   "curso": "CINE1248P",
   "tema": "2",
   "subtema": "2.4",
   "semana": "4",
   "tipo": "Saberes esenciales",
   "formato": "Word",
   "titulo": "Saberes esenciales 2.4: Optimización de recursos",
   "descripcion": "Guía de estudio con fundamentos, autores clave, casos empresariales de la región, glosario y bibliografía APA 7.",
   "enlace": "",
   "enlace_externo": "",
   "etiquetas": "recursos; desperdicios; lean",
   "destacado": "",
   "visibilidad": "Estudiantes",
   "estado": "Activo",
   "actualizado": "2026-09-04",
   "peso": "1,6 MB"
  },
  {
   "id": "CINE1248P-T03-PPT",
   "curso": "CINE1248P",
   "tema": "3",
   "subtema": "",
   "semana": "5",
   "tipo": "Presentación",
   "formato": "PowerPoint",
   "titulo": "PPT del Tema 3: Métodos de trabajo",
   "descripcion": "Presentación de clase que integra los cuatro subtemas del Tema 3.",
   "enlace": "",
   "enlace_externo": "",
   "etiquetas": "tiempo estándar; cronometraje; therbligs; cursograma; DAP; diagrama de proceso; tiempo estándar; suplementos; valoración del ritmo; estadística; muestreo; variabilidad",
   "destacado": "",
   "visibilidad": "Estudiantes",
   "estado": "Activo",
   "actualizado": "2026-09-18",
   "peso": "8,4 MB"
  },
  {
   "id": "CINE1248P-T03-VIDEO",
   "curso": "CINE1248P",
   "tema": "3",
   "subtema": "",
   "semana": "5",
   "tipo": "Video",
   "formato": "Video",
   "titulo": "Video introductorio del Tema 3",
   "descripcion": "Cinco minutos para entender de qué trata métodos de trabajo y qué harás en el laboratorio.",
   "enlace": "",
   "enlace_externo": "",
   "etiquetas": "",
   "destacado": "",
   "visibilidad": "Estudiantes",
   "estado": "Activo",
   "actualizado": "2026-09-18",
   "peso": ""
  },
  {
   "id": "CINE1248P-T03SUBT31",
   "curso": "CINE1248P",
   "tema": "3",
   "subtema": "3.1",
   "semana": "5",
   "tipo": "Saberes esenciales",
   "formato": "Word",
   "titulo": "Saberes esenciales 3.1: Estudio de tiempos y movimientos",
   "descripcion": "Guía de estudio con fundamentos, autores clave, casos empresariales de la región, glosario y bibliografía APA 7.",
   "enlace": "",
   "enlace_externo": "",
   "etiquetas": "tiempo estándar; cronometraje; therbligs",
   "destacado": "⭐",
   "visibilidad": "Estudiantes",
   "estado": "Activo",
   "actualizado": "2026-09-18",
   "peso": "1,6 MB"
  },
  {
   "id": "CINE1248P-T03SUBT32",
   "curso": "CINE1248P",
   "tema": "3",
   "subtema": "3.2",
   "semana": "5",
   "tipo": "Saberes esenciales",
   "formato": "Word",
   "titulo": "Saberes esenciales 3.2: Cursogramas analíticos",
   "descripcion": "Guía de estudio con fundamentos, autores clave, casos empresariales de la región, glosario y bibliografía APA 7.",
   "enlace": "",
   "enlace_externo": "",
   "etiquetas": "cursograma; DAP; diagrama de proceso",
   "destacado": "",
   "visibilidad": "Estudiantes",
   "estado": "Activo",
   "actualizado": "2026-09-18",
   "peso": "1,6 MB"
  },
  {
   "id": "CINE1248P-T03SUBT33",
   "curso": "CINE1248P",
   "tema": "3",
   "subtema": "3.3",
   "semana": "6",
   "tipo": "Saberes esenciales",
   "formato": "Word",
   "titulo": "Saberes esenciales 3.3: Medición del trabajo",
   "descripcion": "Guía de estudio con fundamentos, autores clave, casos empresariales de la región, glosario y bibliografía APA 7.",
   "enlace": "",
   "enlace_externo": "",
   "etiquetas": "tiempo estándar; suplementos; valoración del ritmo",
   "destacado": "",
   "visibilidad": "Estudiantes",
   "estado": "Activo",
   "actualizado": "2026-09-18",
   "peso": "1,6 MB"
  },
  {
   "id": "CINE1248P-T03SUBT34",
   "curso": "CINE1248P",
   "tema": "3",
   "subtema": "3.4",
   "semana": "6",
   "tipo": "Saberes esenciales",
   "formato": "Word",
   "titulo": "Saberes esenciales 3.4: Control estadístico",
   "descripcion": "Guía de estudio con fundamentos, autores clave, casos empresariales de la región, glosario y bibliografía APA 7.",
   "enlace": "",
   "enlace_externo": "",
   "etiquetas": "estadística; muestreo; variabilidad",
   "destacado": "",
   "visibilidad": "Estudiantes",
   "estado": "Activo",
   "actualizado": "2026-09-18",
   "peso": "1,6 MB"
  },
  {
   "id": "CINE1248P-T04-PPT",
   "curso": "CINE1248P",
   "tema": "4",
   "subtema": "",
   "semana": "7",
   "tipo": "Presentación",
   "formato": "PowerPoint",
   "titulo": "PPT del Tema 4: Herramientas de control",
   "descripcion": "Presentación de clase que integra los cuatro subtemas del Tema 4.",
   "enlace": "",
   "enlace_externo": "",
   "etiquetas": "SPC; gráficos de control; Cp; Cpk; KPI; indicadores; OEE; productividad; riesgos; AMFE; matriz de riesgos; Ishikawa; Pareto; 5 porqués",
   "destacado": "",
   "visibilidad": "Estudiantes",
   "estado": "Activo",
   "actualizado": "2026-09-23",
   "peso": "8,4 MB"
  },
  {
   "id": "CINE1248P-T04-VIDEO",
   "curso": "CINE1248P",
   "tema": "4",
   "subtema": "",
   "semana": "7",
   "tipo": "Video",
   "formato": "Video",
   "titulo": "Video introductorio del Tema 4",
   "descripcion": "Cinco minutos para entender de qué trata herramientas de control y qué harás en el laboratorio.",
   "enlace": "",
   "enlace_externo": "",
   "etiquetas": "",
   "destacado": "",
   "visibilidad": "Estudiantes",
   "estado": "Activo",
   "actualizado": "2026-09-23",
   "peso": ""
  },
  {
   "id": "CINE1248P-T04SUBT41",
   "curso": "CINE1248P",
   "tema": "4",
   "subtema": "4.1",
   "semana": "7",
   "tipo": "Saberes esenciales",
   "formato": "Word",
   "titulo": "Saberes esenciales 4.1: Control estadístico de procesos",
   "descripcion": "Guía de estudio con fundamentos, autores clave, casos empresariales de la región, glosario y bibliografía APA 7.",
   "enlace": "",
   "enlace_externo": "",
   "etiquetas": "SPC; gráficos de control; Cp; Cpk",
   "destacado": "",
   "visibilidad": "Estudiantes",
   "estado": "Activo",
   "actualizado": "2026-09-23",
   "peso": "1,6 MB"
  },
  {
   "id": "CINE1248P-T04SUBT42",
   "curso": "CINE1248P",
   "tema": "4",
   "subtema": "4.2",
   "semana": "7",
   "tipo": "Saberes esenciales",
   "formato": "Word",
   "titulo": "Saberes esenciales 4.2: Indicadores de desempeño",
   "descripcion": "Guía de estudio con fundamentos, autores clave, casos empresariales de la región, glosario y bibliografía APA 7.",
   "enlace": "",
   "enlace_externo": "",
   "etiquetas": "KPI; indicadores; OEE; productividad",
   "destacado": "",
   "visibilidad": "Estudiantes",
   "estado": "Activo",
   "actualizado": "2026-09-23",
   "peso": "1,6 MB"
  },
  {
   "id": "CINE1248P-T04SUBT43",
   "curso": "CINE1248P",
   "tema": "4",
   "subtema": "4.3",
   "semana": "9",
   "tipo": "Saberes esenciales",
   "formato": "Word",
   "titulo": "Saberes esenciales 4.3: Gestión de riesgos",
   "descripcion": "Guía de estudio con fundamentos, autores clave, casos empresariales de la región, glosario y bibliografía APA 7.",
   "enlace": "",
   "enlace_externo": "",
   "etiquetas": "riesgos; AMFE; matriz de riesgos",
   "destacado": "",
   "visibilidad": "Estudiantes",
   "estado": "Activo",
   "actualizado": "2026-09-23",
   "peso": "1,6 MB"
  },
  {
   "id": "CINE1248P-T04SUBT44",
   "curso": "CINE1248P",
   "tema": "4",
   "subtema": "4.4",
   "semana": "9",
   "tipo": "Saberes esenciales",
   "formato": "Word",
   "titulo": "Saberes esenciales 4.4: Herramientas cualitativas y cuantitativas",
   "descripcion": "Guía de estudio con fundamentos, autores clave, casos empresariales de la región, glosario y bibliografía APA 7.",
   "enlace": "",
   "enlace_externo": "",
   "etiquetas": "Ishikawa; Pareto; 5 porqués",
   "destacado": "",
   "visibilidad": "Estudiantes",
   "estado": "Activo",
   "actualizado": "2026-09-23",
   "peso": "1,6 MB"
  },
  {
   "id": "CINE1248P-T05-PPT",
   "curso": "CINE1248P",
   "tema": "5",
   "subtema": "",
   "semana": "10",
   "tipo": "Presentación",
   "formato": "PowerPoint",
   "titulo": "PPT del Tema 5: Planificación y programación",
   "descripcion": "Presentación de clase que integra los cuatro subtemas del Tema 5.",
   "enlace": "",
   "enlace_externo": "",
   "etiquetas": "pronósticos; promedio móvil; suavizamiento exponencial; planeación agregada; persecución; nivelación; MRP; lista de materiales; BOM; programación lineal; recursos; Solver",
   "destacado": "",
   "visibilidad": "Estudiantes",
   "estado": "Activo",
   "actualizado": "2026-09-10",
   "peso": "8,4 MB"
  },
  {
   "id": "CINE1248P-T05-VIDEO",
   "curso": "CINE1248P",
   "tema": "5",
   "subtema": "",
   "semana": "10",
   "tipo": "Video",
   "formato": "Video",
   "titulo": "Video introductorio del Tema 5",
   "descripcion": "Cinco minutos para entender de qué trata planificación y programación y qué harás en el laboratorio.",
   "enlace": "",
   "enlace_externo": "",
   "etiquetas": "",
   "destacado": "",
   "visibilidad": "Estudiantes",
   "estado": "Activo",
   "actualizado": "2026-09-10",
   "peso": ""
  },
  {
   "id": "CINE1248P-T05SUBT51",
   "curso": "CINE1248P",
   "tema": "5",
   "subtema": "5.1",
   "semana": "10",
   "tipo": "Saberes esenciales",
   "formato": "Word",
   "titulo": "Saberes esenciales 5.1: Pronósticos",
   "descripcion": "Guía de estudio con fundamentos, autores clave, casos empresariales de la región, glosario y bibliografía APA 7.",
   "enlace": "",
   "enlace_externo": "",
   "etiquetas": "pronósticos; promedio móvil; suavizamiento exponencial",
   "destacado": "",
   "visibilidad": "Estudiantes",
   "estado": "Activo",
   "actualizado": "2026-09-10",
   "peso": "1,6 MB"
  },
  {
   "id": "CINE1248P-T05SUBT52",
   "curso": "CINE1248P",
   "tema": "5",
   "subtema": "5.2",
   "semana": "10",
   "tipo": "Saberes esenciales",
   "formato": "Word",
   "titulo": "Saberes esenciales 5.2: Planeación agregada",
   "descripcion": "Guía de estudio con fundamentos, autores clave, casos empresariales de la región, glosario y bibliografía APA 7.",
   "enlace": "",
   "enlace_externo": "",
   "etiquetas": "planeación agregada; persecución; nivelación",
   "destacado": "",
   "visibilidad": "Estudiantes",
   "estado": "Activo",
   "actualizado": "2026-09-10",
   "peso": "1,6 MB"
  },
  {
   "id": "CINE1248P-T05SUBT53",
   "curso": "CINE1248P",
   "tema": "5",
   "subtema": "5.3",
   "semana": "11",
   "tipo": "Saberes esenciales",
   "formato": "Word",
   "titulo": "Saberes esenciales 5.3: MRP",
   "descripcion": "Guía de estudio con fundamentos, autores clave, casos empresariales de la región, glosario y bibliografía APA 7.",
   "enlace": "",
   "enlace_externo": "",
   "etiquetas": "MRP; lista de materiales; BOM",
   "destacado": "",
   "visibilidad": "Estudiantes",
   "estado": "Activo",
   "actualizado": "2026-09-10",
   "peso": "1,6 MB"
  },
  {
   "id": "CINE1248P-T05SUBT54",
   "curso": "CINE1248P",
   "tema": "5",
   "subtema": "5.4",
   "semana": "11",
   "tipo": "Saberes esenciales",
   "formato": "Word",
   "titulo": "Saberes esenciales 5.4: Optimización de recursos",
   "descripcion": "Guía de estudio con fundamentos, autores clave, casos empresariales de la región, glosario y bibliografía APA 7.",
   "enlace": "",
   "enlace_externo": "",
   "etiquetas": "programación lineal; recursos; Solver",
   "destacado": "",
   "visibilidad": "Estudiantes",
   "estado": "Activo",
   "actualizado": "2026-09-10",
   "peso": "1,6 MB"
  },
  {
   "id": "CINE1248P-T06-PPT",
   "curso": "CINE1248P",
   "tema": "6",
   "subtema": "",
   "semana": "12",
   "tipo": "Presentación",
   "formato": "PowerPoint",
   "titulo": "PPT del Tema 6: Gestión de proyectos",
   "descripcion": "Presentación de clase que integra los cuatro subtemas del Tema 6.",
   "enlace": "",
   "enlace_externo": "",
   "etiquetas": "CPM; ruta crítica; PERT; tiempos probabilísticos; Gantt; cronograma; recursos; VAN; TIR; evaluación de proyectos",
   "destacado": "",
   "visibilidad": "Estudiantes",
   "estado": "Activo",
   "actualizado": "2026-09-10",
   "peso": "8,4 MB"
  },
  {
   "id": "CINE1248P-T06-VIDEO",
   "curso": "CINE1248P",
   "tema": "6",
   "subtema": "",
   "semana": "12",
   "tipo": "Video",
   "formato": "Video",
   "titulo": "Video introductorio del Tema 6",
   "descripcion": "Cinco minutos para entender de qué trata gestión de proyectos y qué harás en el laboratorio.",
   "enlace": "",
   "enlace_externo": "",
   "etiquetas": "",
   "destacado": "",
   "visibilidad": "Estudiantes",
   "estado": "Activo",
   "actualizado": "2026-09-10",
   "peso": ""
  },
  {
   "id": "CINE1248P-T06SUBT61",
   "curso": "CINE1248P",
   "tema": "6",
   "subtema": "6.1",
   "semana": "12",
   "tipo": "Saberes esenciales",
   "formato": "Word",
   "titulo": "Saberes esenciales 6.1: CPM",
   "descripcion": "Guía de estudio con fundamentos, autores clave, casos empresariales de la región, glosario y bibliografía APA 7.",
   "enlace": "",
   "enlace_externo": "",
   "etiquetas": "CPM; ruta crítica",
   "destacado": "",
   "visibilidad": "Estudiantes",
   "estado": "Activo",
   "actualizado": "2026-09-10",
   "peso": "1,6 MB"
  },
  {
   "id": "CINE1248P-T06SUBT62",
   "curso": "CINE1248P",
   "tema": "6",
   "subtema": "6.2",
   "semana": "12",
   "tipo": "Saberes esenciales",
   "formato": "Word",
   "titulo": "Saberes esenciales 6.2: PERT",
   "descripcion": "Guía de estudio con fundamentos, autores clave, casos empresariales de la región, glosario y bibliografía APA 7.",
   "enlace": "",
   "enlace_externo": "",
   "etiquetas": "PERT; tiempos probabilísticos",
   "destacado": "",
   "visibilidad": "Estudiantes",
   "estado": "Activo",
   "actualizado": "2026-09-10",
   "peso": "1,6 MB"
  },
  {
   "id": "CINE1248P-T06SUBT63",
   "curso": "CINE1248P",
   "tema": "6",
   "subtema": "6.3",
   "semana": "13",
   "tipo": "Saberes esenciales",
   "formato": "Word",
   "titulo": "Saberes esenciales 6.3: Cronogramas y recursos",
   "descripcion": "Guía de estudio con fundamentos, autores clave, casos empresariales de la región, glosario y bibliografía APA 7.",
   "enlace": "",
   "enlace_externo": "",
   "etiquetas": "Gantt; cronograma; recursos",
   "destacado": "",
   "visibilidad": "Estudiantes",
   "estado": "Activo",
   "actualizado": "2026-09-10",
   "peso": "1,6 MB"
  },
  {
   "id": "CINE1248P-T06SUBT64",
   "curso": "CINE1248P",
   "tema": "6",
   "subtema": "6.4",
   "semana": "13",
   "tipo": "Saberes esenciales",
   "formato": "Word",
   "titulo": "Saberes esenciales 6.4: Evaluación de proyectos",
   "descripcion": "Guía de estudio con fundamentos, autores clave, casos empresariales de la región, glosario y bibliografía APA 7.",
   "enlace": "",
   "enlace_externo": "",
   "etiquetas": "VAN; TIR; evaluación de proyectos",
   "destacado": "",
   "visibilidad": "Estudiantes",
   "estado": "Activo",
   "actualizado": "2026-09-10",
   "peso": "1,6 MB"
  },
  {
   "id": "CINE1248P-T07-PPT",
   "curso": "CINE1248P",
   "tema": "7",
   "subtema": "",
   "semana": "14",
   "tipo": "Presentación",
   "formato": "PowerPoint",
   "titulo": "PPT del Tema 7: Innovación y tendencias",
   "descripcion": "Presentación de clase que integra los cuatro subtemas del Tema 7.",
   "enlace": "",
   "enlace_externo": "",
   "etiquetas": "producción verde; ecoeficiencia; economía circular; 9R; cradle to cradle; industria 4.0; automatización; IoT; tendencias; retos; transición",
   "destacado": "",
   "visibilidad": "Estudiantes",
   "estado": "Activo",
   "actualizado": "2026-09-10",
   "peso": "8,4 MB"
  },
  {
   "id": "CINE1248P-T07-VIDEO",
   "curso": "CINE1248P",
   "tema": "7",
   "subtema": "",
   "semana": "14",
   "tipo": "Video",
   "formato": "Video",
   "titulo": "Video introductorio del Tema 7",
   "descripcion": "Cinco minutos para entender de qué trata innovación y tendencias y qué harás en el laboratorio.",
   "enlace": "",
   "enlace_externo": "",
   "etiquetas": "",
   "destacado": "",
   "visibilidad": "Estudiantes",
   "estado": "Activo",
   "actualizado": "2026-09-10",
   "peso": ""
  },
  {
   "id": "CINE1248P-T07SUBT71",
   "curso": "CINE1248P",
   "tema": "7",
   "subtema": "7.1",
   "semana": "14",
   "tipo": "Saberes esenciales",
   "formato": "Word",
   "titulo": "Saberes esenciales 7.1: Producción verde",
   "descripcion": "Guía de estudio con fundamentos, autores clave, casos empresariales de la región, glosario y bibliografía APA 7.",
   "enlace": "",
   "enlace_externo": "",
   "etiquetas": "producción verde; ecoeficiencia",
   "destacado": "",
   "visibilidad": "Estudiantes",
   "estado": "Activo",
   "actualizado": "2026-09-10",
   "peso": "1,6 MB"
  },
  {
   "id": "CINE1248P-T07SUBT72",
   "curso": "CINE1248P",
   "tema": "7",
   "subtema": "7.2",
   "semana": "14",
   "tipo": "Saberes esenciales",
   "formato": "Word",
   "titulo": "Saberes esenciales 7.2: Economía circular",
   "descripcion": "Guía de estudio con fundamentos, autores clave, casos empresariales de la región, glosario y bibliografía APA 7.",
   "enlace": "",
   "enlace_externo": "",
   "etiquetas": "economía circular; 9R; cradle to cradle",
   "destacado": "",
   "visibilidad": "Estudiantes",
   "estado": "Activo",
   "actualizado": "2026-09-10",
   "peso": "1,6 MB"
  },
  {
   "id": "CINE1248P-T07SUBT73",
   "curso": "CINE1248P",
   "tema": "7",
   "subtema": "7.3",
   "semana": "15",
   "tipo": "Saberes esenciales",
   "formato": "Word",
   "titulo": "Saberes esenciales 7.3: Digitalización y automatización",
   "descripcion": "Guía de estudio con fundamentos, autores clave, casos empresariales de la región, glosario y bibliografía APA 7.",
   "enlace": "",
   "enlace_externo": "",
   "etiquetas": "industria 4.0; automatización; IoT",
   "destacado": "",
   "visibilidad": "Estudiantes",
   "estado": "Activo",
   "actualizado": "2026-09-10",
   "peso": "1,6 MB"
  },
  {
   "id": "CINE1248P-T07SUBT74",
   "curso": "CINE1248P",
   "tema": "7",
   "subtema": "7.4",
   "semana": "15",
   "tipo": "Saberes esenciales",
   "formato": "Word",
   "titulo": "Saberes esenciales 7.4: Retos futuros de la producción sostenible",
   "descripcion": "Guía de estudio con fundamentos, autores clave, casos empresariales de la región, glosario y bibliografía APA 7.",
   "enlace": "",
   "enlace_externo": "",
   "etiquetas": "tendencias; retos; transición",
   "destacado": "",
   "visibilidad": "Estudiantes",
   "estado": "Activo",
   "actualizado": "2026-09-10",
   "peso": "1,6 MB"
  },
  {
   "id": "CINE1248P-T01-GUIA",
   "curso": "CINE1248P",
   "tema": "1",
   "subtema": "",
   "semana": "2",
   "tipo": "Guía",
   "formato": "PDF",
   "titulo": "Guía de laboratorio 1: Diagnóstico de sostenibilidad de una empresa cajamarquina",
   "descripcion": "Evaluar las prácticas sostenibles de una empresa local con la matriz de impactos.",
   "enlace": "",
   "enlace_externo": "",
   "etiquetas": "sostenibilidad; triple resultado; ODS; ODS; economía verde; triple resultado",
   "destacado": "",
   "visibilidad": "Estudiantes",
   "estado": "Activo",
   "actualizado": "2026-08-22",
   "peso": "0,9 MB"
  },
  {
   "id": "CINE1248P-T01-RUB",
   "curso": "CINE1248P",
   "tema": "1",
   "subtema": "",
   "semana": "2",
   "tipo": "Rúbrica",
   "formato": "PDF",
   "titulo": "Rúbrica del laboratorio 1",
   "descripcion": "Criterios y niveles de logro en escala vigesimal (0–20).",
   "enlace": "",
   "enlace_externo": "",
   "etiquetas": "rúbrica; evaluación; laboratorio",
   "destacado": "",
   "visibilidad": "Estudiantes",
   "estado": "Activo",
   "actualizado": "2026-08-22",
   "peso": "0,3 MB"
  },
  {
   "id": "CINE1248P-T02-GUIA",
   "curso": "CINE1248P",
   "tema": "2",
   "subtema": "",
   "semana": "4",
   "tipo": "Guía",
   "formato": "PDF",
   "titulo": "Guía de laboratorio 2: Rediseño del layout de una planta de lácteos",
   "descripcion": "Proponer una distribución que reduzca recorridos y riesgos ergonómicos.",
   "enlace": "",
   "enlace_externo": "",
   "etiquetas": "layout; distribución de planta; SLP; localización; factores ponderados; centro de gravedad",
   "destacado": "",
   "visibilidad": "Estudiantes",
   "estado": "Activo",
   "actualizado": "2026-09-04",
   "peso": "0,9 MB"
  },
  {
   "id": "CINE1248P-T02-RUB",
   "curso": "CINE1248P",
   "tema": "2",
   "subtema": "",
   "semana": "4",
   "tipo": "Rúbrica",
   "formato": "PDF",
   "titulo": "Rúbrica del laboratorio 2",
   "descripcion": "Criterios y niveles de logro en escala vigesimal (0–20).",
   "enlace": "",
   "enlace_externo": "",
   "etiquetas": "rúbrica; evaluación; laboratorio",
   "destacado": "",
   "visibilidad": "Estudiantes",
   "estado": "Activo",
   "actualizado": "2026-09-04",
   "peso": "0,3 MB"
  },
  {
   "id": "CINE1248P-T03-GUIA",
   "curso": "CINE1248P",
   "tema": "3",
   "subtema": "",
   "semana": "6",
   "tipo": "Guía",
   "formato": "PDF",
   "titulo": "Guía de laboratorio 3: Estudio de tiempos y cursograma analítico",
   "descripcion": "Calcular el tiempo estándar de una operación y representarla en un cursograma.",
   "enlace": "",
   "enlace_externo": "",
   "etiquetas": "tiempo estándar; cronometraje; therbligs; cursograma; DAP; diagrama de proceso",
   "destacado": "🔥",
   "visibilidad": "Estudiantes",
   "estado": "Activo",
   "actualizado": "2026-09-18",
   "peso": "0,9 MB"
  },
  {
   "id": "CINE1248P-T03-RUB",
   "curso": "CINE1248P",
   "tema": "3",
   "subtema": "",
   "semana": "6",
   "tipo": "Rúbrica",
   "formato": "PDF",
   "titulo": "Rúbrica del laboratorio 3",
   "descripcion": "Criterios y niveles de logro en escala vigesimal (0–20).",
   "enlace": "",
   "enlace_externo": "",
   "etiquetas": "rúbrica; evaluación; laboratorio",
   "destacado": "",
   "visibilidad": "Estudiantes",
   "estado": "Activo",
   "actualizado": "2026-09-18",
   "peso": "0,3 MB"
  },
  {
   "id": "CINE1248P-T04-GUIA",
   "curso": "CINE1248P",
   "tema": "4",
   "subtema": "",
   "semana": "9",
   "tipo": "Guía",
   "formato": "PDF",
   "titulo": "Guía de laboratorio 4: Cálculo del OEE y gráficos de control",
   "descripcion": "Medir la eficiencia global de los equipos (OEE) y analizar la estabilidad del proceso.",
   "enlace": "",
   "enlace_externo": "",
   "etiquetas": "SPC; gráficos de control; Cp; Cpk; KPI; indicadores; OEE; productividad; OEE; eficiencia global de los equipos",
   "destacado": "",
   "visibilidad": "Estudiantes",
   "estado": "Activo",
   "actualizado": "2026-09-23",
   "peso": "0,9 MB"
  },
  {
   "id": "CINE1248P-T04-RUB",
   "curso": "CINE1248P",
   "tema": "4",
   "subtema": "",
   "semana": "9",
   "tipo": "Rúbrica",
   "formato": "PDF",
   "titulo": "Rúbrica del laboratorio 4",
   "descripcion": "Criterios y niveles de logro en escala vigesimal (0–20).",
   "enlace": "",
   "enlace_externo": "",
   "etiquetas": "rúbrica; evaluación; laboratorio",
   "destacado": "",
   "visibilidad": "Estudiantes",
   "estado": "Activo",
   "actualizado": "2026-09-23",
   "peso": "0,3 MB"
  },
  {
   "id": "CINE1248P-T05-GUIA",
   "curso": "CINE1248P",
   "tema": "5",
   "subtema": "",
   "semana": "11",
   "tipo": "Guía",
   "formato": "PDF",
   "titulo": "Guía de laboratorio 5: Plan agregado y MRP de un producto agroindustrial",
   "descripcion": "Elaborar un plan de producción y las necesidades de materiales.",
   "enlace": "",
   "enlace_externo": "",
   "etiquetas": "pronósticos; promedio móvil; suavizamiento exponencial; planeación agregada; persecución; nivelación",
   "destacado": "",
   "visibilidad": "Estudiantes",
   "estado": "Activo",
   "actualizado": "2026-09-10",
   "peso": "0,9 MB"
  },
  {
   "id": "CINE1248P-T05-RUB",
   "curso": "CINE1248P",
   "tema": "5",
   "subtema": "",
   "semana": "11",
   "tipo": "Rúbrica",
   "formato": "PDF",
   "titulo": "Rúbrica del laboratorio 5",
   "descripcion": "Criterios y niveles de logro en escala vigesimal (0–20).",
   "enlace": "",
   "enlace_externo": "",
   "etiquetas": "rúbrica; evaluación; laboratorio",
   "destacado": "",
   "visibilidad": "Estudiantes",
   "estado": "Activo",
   "actualizado": "2026-09-10",
   "peso": "0,3 MB"
  },
  {
   "id": "CINE1248P-T06-GUIA",
   "curso": "CINE1248P",
   "tema": "6",
   "subtema": "",
   "semana": "13",
   "tipo": "Guía",
   "formato": "PDF",
   "titulo": "Guía de laboratorio 6: Cronograma CPM/PERT del proyecto de mejora",
   "descripcion": "Programar el proyecto de mejora y determinar su ruta crítica.",
   "enlace": "",
   "enlace_externo": "",
   "etiquetas": "CPM; ruta crítica; PERT; tiempos probabilísticos",
   "destacado": "",
   "visibilidad": "Estudiantes",
   "estado": "Activo",
   "actualizado": "2026-09-10",
   "peso": "0,9 MB"
  },
  {
   "id": "CINE1248P-T06-RUB",
   "curso": "CINE1248P",
   "tema": "6",
   "subtema": "",
   "semana": "13",
   "tipo": "Rúbrica",
   "formato": "PDF",
   "titulo": "Rúbrica del laboratorio 6",
   "descripcion": "Criterios y niveles de logro en escala vigesimal (0–20).",
   "enlace": "",
   "enlace_externo": "",
   "etiquetas": "rúbrica; evaluación; laboratorio",
   "destacado": "",
   "visibilidad": "Estudiantes",
   "estado": "Activo",
   "actualizado": "2026-09-10",
   "peso": "0,3 MB"
  },
  {
   "id": "CINE1248P-T07-GUIA",
   "curso": "CINE1248P",
   "tema": "7",
   "subtema": "",
   "semana": "15",
   "tipo": "Guía",
   "formato": "PDF",
   "titulo": "Guía de laboratorio 7: Propuesta de economía circular",
   "descripcion": "Diseñar una estrategia circular para el proceso productivo elegido.",
   "enlace": "",
   "enlace_externo": "",
   "etiquetas": "producción verde; ecoeficiencia; economía circular; 9R; cradle to cradle",
   "destacado": "",
   "visibilidad": "Estudiantes",
   "estado": "Activo",
   "actualizado": "2026-09-10",
   "peso": "0,9 MB"
  },
  {
   "id": "CINE1248P-T07-RUB",
   "curso": "CINE1248P",
   "tema": "7",
   "subtema": "",
   "semana": "15",
   "tipo": "Rúbrica",
   "formato": "PDF",
   "titulo": "Rúbrica del laboratorio 7",
   "descripcion": "Criterios y niveles de logro en escala vigesimal (0–20).",
   "enlace": "",
   "enlace_externo": "",
   "etiquetas": "rúbrica; evaluación; laboratorio",
   "destacado": "",
   "visibilidad": "Estudiantes",
   "estado": "Activo",
   "actualizado": "2026-09-10",
   "peso": "0,3 MB"
  },
  {
   "id": "CINE1248P-PLT-OEE",
   "curso": "CINE1248P",
   "tema": "4",
   "subtema": "4.2",
   "semana": "8",
   "tipo": "Plantilla",
   "formato": "Excel",
   "titulo": "Calculadora de OEE",
   "descripcion": "Registra disponibilidad, rendimiento y calidad; calcula el OEE por turno y lo grafica.",
   "enlace": "",
   "enlace_externo": "",
   "etiquetas": "OEE; eficiencia global de los equipos; KPI; productividad",
   "destacado": "🔥",
   "visibilidad": "Estudiantes",
   "estado": "Activo",
   "actualizado": "2026-09-22",
   "peso": "0,2 MB"
  },
  {
   "id": "CINE1248P-PLT-CURSO",
   "curso": "CINE1248P",
   "tema": "3",
   "subtema": "3.2",
   "semana": "5",
   "tipo": "Plantilla",
   "formato": "Excel",
   "titulo": "Plantilla de cursograma analítico",
   "descripcion": "Formato con símbolos ASME, distancias y tiempos, con resumen automático.",
   "enlace": "",
   "enlace_externo": "",
   "etiquetas": "cursograma; DAP; ASME",
   "destacado": "",
   "visibilidad": "Estudiantes",
   "estado": "Activo",
   "actualizado": "2026-09-15",
   "peso": "0,2 MB"
  },
  {
   "id": "CINE1248P-PLT-CRONO",
   "curso": "CINE1248P",
   "tema": "3",
   "subtema": "3.1",
   "semana": "5",
   "tipo": "Plantilla",
   "formato": "Excel",
   "titulo": "Hoja de cronometraje y tiempo estándar",
   "descripcion": "Registra 10 ciclos, aplica valoración y suplementos y obtiene el tiempo estándar.",
   "enlace": "",
   "enlace_externo": "",
   "etiquetas": "tiempo estándar; cronometraje; suplementos",
   "destacado": "",
   "visibilidad": "Estudiantes",
   "estado": "Activo",
   "actualizado": "2026-09-15",
   "peso": "0,2 MB"
  },
  {
   "id": "CINE1248P-PLT-EF",
   "curso": "CINE1248P",
   "tema": "",
   "subtema": "",
   "semana": "15",
   "tipo": "Plantilla",
   "formato": "Word",
   "titulo": "Plantilla del reporte académico final (EF)",
   "descripcion": "Estructura obligatoria del reporte: diagnóstico, propuesta de optimización, impacto sostenible y referencias APA 7.",
   "enlace": "",
   "enlace_externo": "",
   "etiquetas": "evaluación final; EF; informe; reporte",
   "destacado": "📌",
   "visibilidad": "Estudiantes",
   "estado": "Activo",
   "actualizado": "2026-09-15",
   "peso": "0,2 MB"
  },
  {
   "id": "CINE1248P-PLT-EP",
   "curso": "CINE1248P",
   "tema": "",
   "subtema": "",
   "semana": "10",
   "tipo": "Plantilla",
   "formato": "PowerPoint",
   "titulo": "Plantilla de sustentación del avance (EP)",
   "descripcion": "Diapositivas base para presentar el avance del desafío del curso en 10 minutos.",
   "enlace": "",
   "enlace_externo": "",
   "etiquetas": "EP; exposición; sustentación",
   "destacado": "",
   "visibilidad": "Estudiantes",
   "estado": "Activo",
   "actualizado": "2026-09-15",
   "peso": "0,2 MB"
  },
  {
   "id": "CINE1248P-PLT-GANTT",
   "curso": "CINE1248P",
   "tema": "6",
   "subtema": "6.3",
   "semana": "12",
   "tipo": "Plantilla",
   "formato": "Excel",
   "titulo": "Plantilla CPM/PERT y Gantt",
   "descripcion": "Calcula holguras y ruta crítica y dibuja el Gantt automáticamente.",
   "enlace": "",
   "enlace_externo": "",
   "etiquetas": "CPM; PERT; Gantt; ruta crítica",
   "destacado": "",
   "visibilidad": "Estudiantes",
   "estado": "Activo",
   "actualizado": "2026-09-15",
   "peso": "0,2 MB"
  },
  {
   "id": "CINE1248P-HER-IMPACTO",
   "curso": "CINE1248P",
   "tema": "1",
   "subtema": "1.4",
   "semana": "2",
   "tipo": "Herramienta",
   "formato": "Excel",
   "titulo": "Matriz de identificación de impactos ambientales",
   "descripcion": "Matriz tipo Leopold simplificada para valorar impactos por etapa del proceso.",
   "enlace": "",
   "enlace_externo": "",
   "etiquetas": "impacto ambiental; Leopold; matriz",
   "destacado": "",
   "visibilidad": "Estudiantes",
   "estado": "Activo",
   "actualizado": "2026-09-15",
   "peso": "0,2 MB"
  },
  {
   "id": "CINE1248P-HER-REBA",
   "curso": "CINE1248P",
   "tema": "2",
   "subtema": "2.3",
   "semana": "4",
   "tipo": "Herramienta",
   "formato": "PDF",
   "titulo": "Ficha de evaluación ergonómica REBA",
   "descripcion": "Ficha para evaluar posturas de trabajo y priorizar mejoras.",
   "enlace": "",
   "enlace_externo": "",
   "etiquetas": "ergonomía; REBA; postura",
   "destacado": "",
   "visibilidad": "Estudiantes",
   "estado": "Activo",
   "actualizado": "2026-09-15",
   "peso": "0,2 MB"
  },
  {
   "id": "CINE1248P-HER-ISHI",
   "curso": "CINE1248P",
   "tema": "4",
   "subtema": "4.4",
   "semana": "9",
   "tipo": "Herramienta",
   "formato": "PowerPoint",
   "titulo": "Diagrama de Ishikawa editable",
   "descripcion": "Diagrama causa-efecto 6M listo para completar en equipo.",
   "enlace": "",
   "enlace_externo": "",
   "etiquetas": "Ishikawa; causa-efecto; 6M",
   "destacado": "",
   "visibilidad": "Estudiantes",
   "estado": "Activo",
   "actualizado": "2026-09-15",
   "peso": "0,2 MB"
  },
  {
   "id": "CINE1248P-HER-CANVAS",
   "curso": "CINE1248P",
   "tema": "7",
   "subtema": "7.2",
   "semana": "15",
   "tipo": "Herramienta",
   "formato": "PDF",
   "titulo": "Canvas de economía circular",
   "descripcion": "Lienzo para mapear flujos de materiales, estrategias 9R y modelo de negocio circular.",
   "enlace": "",
   "enlace_externo": "",
   "etiquetas": "economía circular; canvas; 9R",
   "destacado": "⭐",
   "visibilidad": "Estudiantes",
   "estado": "Activo",
   "actualizado": "2026-09-15",
   "peso": "0,2 MB"
  },
  {
   "id": "CINE1248P-HER-SLP",
   "curso": "CINE1248P",
   "tema": "2",
   "subtema": "2.1",
   "semana": "3",
   "tipo": "Herramienta",
   "formato": "Excel",
   "titulo": "Tabla relacional de actividades (SLP)",
   "descripcion": "Matriz de cercanía para planificar la distribución de planta.",
   "enlace": "",
   "enlace_externo": "",
   "etiquetas": "SLP; layout; distribución",
   "destacado": "",
   "visibilidad": "Estudiantes",
   "estado": "Activo",
   "actualizado": "2026-09-15",
   "peso": "0,2 MB"
  },
  {
   "id": "CINE1248P-SILABO",
   "curso": "CINE1248P",
   "tema": "",
   "subtema": "",
   "semana": "",
   "tipo": "Documento",
   "formato": "PDF",
   "titulo": "Sílabo CINE1248P 2026-2",
   "descripcion": "Logro del curso, temas, sistema de evaluación (T1, T2, EP, T3, EF) y bibliografía.",
   "enlace": "",
   "enlace_externo": "",
   "etiquetas": "sílabo; evaluación; cronograma",
   "destacado": "📌",
   "visibilidad": "Estudiantes",
   "estado": "Activo",
   "actualizado": "2026-08-20",
   "peso": "0,5 MB"
  },
  {
   "id": "CINE1248P-RUB-EP",
   "curso": "CINE1248P",
   "tema": "",
   "subtema": "",
   "semana": "10",
   "tipo": "Rúbrica",
   "formato": "PDF",
   "titulo": "Rúbrica de la evaluación parcial (EP)",
   "descripcion": "Criterios para la presentación y sustentación del avance del desafío del curso.",
   "enlace": "",
   "enlace_externo": "",
   "etiquetas": "EP; rúbrica; sustentación",
   "destacado": "",
   "visibilidad": "Estudiantes",
   "estado": "Activo",
   "actualizado": "2026-09-15",
   "peso": ""
  },
  {
   "id": "CINE1248P-RUB-EF",
   "curso": "CINE1248P",
   "tema": "",
   "subtema": "",
   "semana": "15",
   "tipo": "Rúbrica",
   "formato": "PDF",
   "titulo": "Rúbrica de la evaluación final (EF)",
   "descripcion": "Criterios del reporte académico final: diagnóstico, propuesta, impacto sostenible y sustentación.",
   "enlace": "",
   "enlace_externo": "",
   "etiquetas": "EF; rúbrica; reporte",
   "destacado": "",
   "visibilidad": "Estudiantes",
   "estado": "Activo",
   "actualizado": "2026-09-15",
   "peso": ""
  },
  {
   "id": "CINE1248P-LEC-HEIZER",
   "curso": "CINE1248P",
   "tema": "1",
   "subtema": "1.2",
   "semana": "1",
   "tipo": "Lectura",
   "formato": "Enlace",
   "titulo": "Heizer, Munson y Render (2021): Principios de administración de operaciones",
   "descripcion": "Texto complementario del sílabo. Consúltalo en la biblioteca virtual UPN.",
   "enlace": "",
   "enlace_externo": "",
   "etiquetas": "bibliografía; Heizer; operaciones",
   "destacado": "",
   "visibilidad": "Estudiantes",
   "estado": "Activo",
   "actualizado": "2026-08-20",
   "peso": ""
  },
  {
   "id": "CINE1248P-INF-OEE",
   "curso": "CINE1248P",
   "tema": "4",
   "subtema": "4.2",
   "semana": "8",
   "tipo": "Infografía",
   "formato": "Imagen",
   "titulo": "Infografía: el OEE en una página",
   "descripcion": "Disponibilidad × Rendimiento × Calidad, con un ejemplo resuelto de una planta de lácteos.",
   "enlace": "",
   "enlace_externo": "",
   "etiquetas": "OEE; eficiencia global de los equipos; KPI",
   "destacado": "🆕",
   "visibilidad": "Estudiantes",
   "estado": "Activo",
   "actualizado": "2026-09-23",
   "peso": "0,7 MB"
  }
 ],
 "actividades": [
  {
   "id": "CINE1248P-ACT-T01",
   "curso": "CINE1248P",
   "tema": "1",
   "semana": "2",
   "nombre": "Laboratorio 1: Diagnóstico de sostenibilidad de una empresa cajamarquina",
   "objetivo": "Evaluar las prácticas sostenibles de una empresa local con la matriz de impactos.",
   "instrucciones": "Trabajo en equipos de 4. Lee la guía antes de la sesión, desarrolla el caso con la plantilla indicada y sube el producto al aula virtual.",
   "producto": "Matriz de impactos completada e informe de 2 páginas.",
   "criterios": "Precisión del análisis (8) · Uso de la herramienta (6) · Propuesta sostenible (4) · Presentación (2)",
   "evaluacion": "",
   "guia": "CINE1248P-T01-GUIA",
   "plantilla": "CINE1248P-HER-IMPACTO",
   "rubrica": "CINE1248P-T01-RUB"
  },
  {
   "id": "CINE1248P-ACT-T02",
   "curso": "CINE1248P",
   "tema": "2",
   "semana": "4",
   "nombre": "Laboratorio 2: Rediseño del layout de una planta de lácteos",
   "objetivo": "Proponer una distribución que reduzca recorridos y riesgos ergonómicos.",
   "instrucciones": "Trabajo en equipos de 4. Lee la guía antes de la sesión, desarrolla el caso con la plantilla indicada y sube el producto al aula virtual.",
   "producto": "Plano actual y propuesto, con cálculo de distancias recorridas.",
   "criterios": "Precisión del análisis (8) · Uso de la herramienta (6) · Propuesta sostenible (4) · Presentación (2)",
   "evaluacion": "",
   "guia": "CINE1248P-T02-GUIA",
   "plantilla": "CINE1248P-HER-SLP",
   "rubrica": "CINE1248P-T02-RUB"
  },
  {
   "id": "CINE1248P-ACT-T03",
   "curso": "CINE1248P",
   "tema": "3",
   "semana": "6",
   "nombre": "Laboratorio 3: Estudio de tiempos y cursograma analítico",
   "objetivo": "Calcular el tiempo estándar de una operación y representarla en un cursograma.",
   "instrucciones": "Trabajo en equipos de 4. Lee la guía antes de la sesión, desarrolla el caso con la plantilla indicada y sube el producto al aula virtual.",
   "producto": "Hoja de cronometraje, tiempo estándar y cursograma analítico.",
   "criterios": "Precisión del análisis (8) · Uso de la herramienta (6) · Propuesta sostenible (4) · Presentación (2)",
   "evaluacion": "",
   "guia": "CINE1248P-T03-GUIA",
   "plantilla": "CINE1248P-PLT-CRONO",
   "rubrica": "CINE1248P-T03-RUB"
  },
  {
   "id": "CINE1248P-ACT-T04",
   "curso": "CINE1248P",
   "tema": "4",
   "semana": "9",
   "nombre": "Laboratorio 4: Cálculo del OEE y gráficos de control",
   "objetivo": "Medir la eficiencia global de los equipos (OEE) y analizar la estabilidad del proceso.",
   "instrucciones": "Trabajo en equipos de 4. Lee la guía antes de la sesión, desarrolla el caso con la plantilla indicada y sube el producto al aula virtual.",
   "producto": "Hoja de cálculo con OEE, gráfico X-R y conclusiones.",
   "criterios": "Precisión del análisis (8) · Uso de la herramienta (6) · Propuesta sostenible (4) · Presentación (2)",
   "evaluacion": "",
   "guia": "CINE1248P-T04-GUIA",
   "plantilla": "CINE1248P-PLT-OEE",
   "rubrica": "CINE1248P-T04-RUB"
  },
  {
   "id": "CINE1248P-ACT-T05",
   "curso": "CINE1248P",
   "tema": "5",
   "semana": "11",
   "nombre": "Laboratorio 5: Plan agregado y MRP de un producto agroindustrial",
   "objetivo": "Elaborar un plan de producción y las necesidades de materiales.",
   "instrucciones": "Trabajo en equipos de 4. Lee la guía antes de la sesión, desarrolla el caso con la plantilla indicada y sube el producto al aula virtual.",
   "producto": "Plan agregado comparado y tabla MRP.",
   "criterios": "Precisión del análisis (8) · Uso de la herramienta (6) · Propuesta sostenible (4) · Presentación (2)",
   "evaluacion": "",
   "guia": "CINE1248P-T05-GUIA",
   "plantilla": "",
   "rubrica": "CINE1248P-T05-RUB"
  },
  {
   "id": "CINE1248P-ACT-T06",
   "curso": "CINE1248P",
   "tema": "6",
   "semana": "13",
   "nombre": "Laboratorio 6: Cronograma CPM/PERT del proyecto de mejora",
   "objetivo": "Programar el proyecto de mejora y determinar su ruta crítica.",
   "instrucciones": "Trabajo en equipos de 4. Lee la guía antes de la sesión, desarrolla el caso con la plantilla indicada y sube el producto al aula virtual.",
   "producto": "Red del proyecto, ruta crítica y diagrama de Gantt.",
   "criterios": "Precisión del análisis (8) · Uso de la herramienta (6) · Propuesta sostenible (4) · Presentación (2)",
   "evaluacion": "",
   "guia": "CINE1248P-T06-GUIA",
   "plantilla": "CINE1248P-PLT-GANTT",
   "rubrica": "CINE1248P-T06-RUB"
  },
  {
   "id": "CINE1248P-ACT-T07",
   "curso": "CINE1248P",
   "tema": "7",
   "semana": "15",
   "nombre": "Laboratorio 7: Propuesta de economía circular",
   "objetivo": "Diseñar una estrategia circular para el proceso productivo elegido.",
   "instrucciones": "Trabajo en equipos de 4. Lee la guía antes de la sesión, desarrolla el caso con la plantilla indicada y sube el producto al aula virtual.",
   "producto": "Canvas de economía circular y pitch de 3 minutos.",
   "criterios": "Precisión del análisis (8) · Uso de la herramienta (6) · Propuesta sostenible (4) · Presentación (2)",
   "evaluacion": "",
   "guia": "CINE1248P-T07-GUIA",
   "plantilla": "CINE1248P-HER-CANVAS",
   "rubrica": "CINE1248P-T07-RUB"
  },
  {
   "id": "CINE1248P-ACT-EP",
   "curso": "CINE1248P",
   "tema": "",
   "semana": "10",
   "nombre": "Evaluación parcial (EP): avance del desafío del curso",
   "objetivo": "Presentar y sustentar el diagnóstico del proceso productivo de la organización elegida.",
   "instrucciones": "Exposición de 10 minutos por equipo más 5 de preguntas. Todos los integrantes sustentan.",
   "producto": "Presentación con diagnóstico, indicadores actuales y oportunidades de mejora.",
   "criterios": "Ver rúbrica EP (escala 0–20). Peso: 20 %.",
   "evaluacion": "EP · 20 %",
   "guia": "",
   "plantilla": "CINE1248P-PLT-EP",
   "rubrica": "CINE1248P-RUB-EP"
  },
  {
   "id": "CINE1248P-ACT-EF",
   "curso": "CINE1248P",
   "tema": "",
   "semana": "15",
   "nombre": "Evaluación final (EF): reporte académico",
   "objetivo": "Sustentar una propuesta de optimización del proceso productivo de una organización real con enfoque sostenible.",
   "instrucciones": "Entrega del reporte en semana 15 y sustentación en semana 16.",
   "producto": "Reporte académico con propuesta de optimización e impacto en eficiencia y responsabilidad social.",
   "criterios": "Ver rúbrica EF (escala 0–20). Peso: 50 %.",
   "evaluacion": "EF · 50 %",
   "guia": "",
   "plantilla": "CINE1248P-PLT-EF",
   "rubrica": "CINE1248P-RUB-EF"
  }
 ],
 "sinonimos": [
  {
   "termino": "OEE",
   "equivalentes": "eficiencia global de los equipos; overall equipment effectiveness"
  },
  {
   "termino": "KPI",
   "equivalentes": "indicador; indicadores de desempeño"
  },
  {
   "termino": "SPC",
   "equivalentes": "control estadístico de procesos; gráficos de control"
  },
  {
   "termino": "CPM",
   "equivalentes": "ruta crítica; método del camino crítico"
  },
  {
   "termino": "MRP",
   "equivalentes": "planeación de requerimientos de materiales; lista de materiales"
  },
  {
   "termino": "DAP",
   "equivalentes": "diagrama de análisis de procesos; cursograma"
  },
  {
   "termino": "layout",
   "equivalentes": "distribución de planta"
  },
  {
   "termino": "EF",
   "equivalentes": "evaluación final; examen final; reporte final"
  },
  {
   "termino": "EP",
   "equivalentes": "evaluación parcial; examen parcial"
  },
  {
   "termino": "ACV",
   "equivalentes": "análisis de ciclo de vida"
  }
 ]
};
